// src/catalog/feedback/badge/Badge.tsx
import type { ReactNode } from "react";

type BadgeColor = "gray" | "blue" | "green" | "amber" | "red" | "purple";
type BadgeVariant = "solid" | "soft" | "dot";

interface BadgeProps {
  color?: BadgeColor;
  variant?: BadgeVariant;
  children: ReactNode;
}

const solidStyles: Record<BadgeColor, string> = {
  gray: "bg-slate-500 text-white",
  blue: "bg-sky-500 text-white",
  green: "bg-emerald-500 text-white",
  amber: "bg-amber-500 text-slate-900",
  red: "bg-rose-500 text-white",
  purple: "bg-violet-500 text-white",
};

const softStyles: Record<BadgeColor, string> = {
  gray: "bg-slate-500/15 text-slate-300",
  blue: "bg-sky-500/15 text-sky-300",
  green: "bg-emerald-500/15 text-emerald-300",
  amber: "bg-amber-500/15 text-amber-300",
  red: "bg-rose-500/15 text-rose-300",
  purple: "bg-violet-500/15 text-violet-300",
};

const dotColors: Record<BadgeColor, string> = {
  gray: "bg-slate-400",
  blue: "bg-sky-400",
  green: "bg-emerald-400",
  amber: "bg-amber-400",
  red: "bg-rose-400",
  purple: "bg-violet-400",
};

export function Badge({ color = "gray", variant = "soft", children }: BadgeProps) {
  const base =
    "inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium";

  if (variant === "dot") {
    return (
      <span className={`${base} ${softStyles[color]}`}>
        <span className={`h-1.5 w-1.5 rounded-full ${dotColors[color]}`} />
        {children}
      </span>
    );
  }

  const palette = variant === "solid" ? solidStyles[color] : softStyles[color];
  return <span className={`${base} ${palette}`}>{children}</span>;
}

// src/catalog/feedback/badge/Badge.svelte
<script lang="ts">
  type BadgeColor = "gray" | "blue" | "green" | "amber" | "red" | "purple";
  type BadgeVariant = "solid" | "soft" | "dot";

  export let color: BadgeColor = "gray";
  export let variant: BadgeVariant = "soft";
  export let label: string = "";
</script>

<span class="badge badge--{variant} badge--{color}">
  {#if variant === "dot"}
    <span class="badge__dot"></span>
  {/if}
  {label}
</span>

<style>
  .badge {
    display: inline-flex;
    align-items: center;
    gap: 0.375rem;
    border-radius: 9999px;
    padding: 0.125rem 0.625rem;
    font-size: 0.75rem;
    font-weight: 500;
    line-height: 1.25rem;
  }

  .badge__dot {
    height: 0.375rem;
    width: 0.375rem;
    border-radius: 9999px;
    background: currentColor;
  }

  /* Solid */
  .badge--solid.badge--gray {
    background: #64748b;
    color: #fff;
  }
  .badge--solid.badge--blue {
    background: #0ea5e9;
    color: #fff;
  }
  .badge--solid.badge--green {
    background: #10b981;
    color: #fff;
  }
  .badge--solid.badge--amber {
    background: #f59e0b;
    color: #0f172a;
  }
  .badge--solid.badge--red {
    background: #f43f5e;
    color: #fff;
  }
  .badge--solid.badge--purple {
    background: #8b5cf6;
    color: #fff;
  }

  /* Soft + dot share the translucent palette */
  .badge--soft.badge--gray,
  .badge--dot.badge--gray {
    background: rgba(100, 116, 139, 0.15);
    color: #cbd5e1;
  }
  .badge--soft.badge--blue,
  .badge--dot.badge--blue {
    background: rgba(14, 165, 233, 0.15);
    color: #7dd3fc;
  }
  .badge--soft.badge--green,
  .badge--dot.badge--green {
    background: rgba(16, 185, 129, 0.15);
    color: #6ee7b7;
  }
  .badge--soft.badge--amber,
  .badge--dot.badge--amber {
    background: rgba(245, 158, 11, 0.15);
    color: #fcd34d;
  }
  .badge--soft.badge--red,
  .badge--dot.badge--red {
    background: rgba(244, 63, 94, 0.15);
    color: #fda4af;
  }
  .badge--soft.badge--purple,
  .badge--dot.badge--purple {
    background: rgba(139, 92, 246, 0.15);
    color: #c4b5fd;
  }

  /* The dot uses currentColor, which matches the soft text tone above. */
</style>
