// src/catalog/data-display/avatar/Avatar.svelte
<script lang="ts">
  type AvatarSize = "sm" | "md" | "lg" | "xl";

  export let name: string;
  export let size: AvatarSize = "md";
  export let online: boolean | undefined = undefined;

  const palette = [
    "#f43f5e",
    "#f97316",
    "#f59e0b",
    "#10b981",
    "#14b8a6",
    "#0ea5e9",
    "#6366f1",
    "#8b5cf6",
    "#d946ef",
  ];

  function initials(value: string) {
    const parts = value.trim().split(/\s+/);
    const first = parts[0]?.[0] ?? "";
    const last = parts.length > 1 ? parts[parts.length - 1][0] : "";
    return (first + last).toUpperCase();
  }

  function colorFor(value: string) {
    let hash = 0;
    for (let i = 0; i < value.length; i++) {
      hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
    }
    return palette[hash % palette.length];
  }

  $: bg = colorFor(name);
  $: text = initials(name);
</script>

<span class="avatar-wrap">
  <span class="avatar avatar--{size}" style="background-color: {bg};" title={name}>
    {text}
  </span>
  {#if online !== undefined}
    <span class="dot dot--{size}" class:dot--online={online}></span>
  {/if}
</span>

<style>
  .avatar-wrap {
    position: relative;
    display: inline-flex;
  }

  .avatar {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 9999px;
    font-weight: 600;
    color: #fff;
    user-select: none;
  }

  .avatar--sm {
    height: 2rem;
    width: 2rem;
    font-size: 0.75rem;
  }
  .avatar--md {
    height: 2.5rem;
    width: 2.5rem;
    font-size: 0.875rem;
  }
  .avatar--lg {
    height: 3.5rem;
    width: 3.5rem;
    font-size: 1.125rem;
  }
  .avatar--xl {
    height: 5rem;
    width: 5rem;
    font-size: 1.5rem;
  }

  .dot {
    position: absolute;
    bottom: 0;
    right: 0;
    border-radius: 9999px;
    background: #64748b;
    box-shadow: 0 0 0 2px #0d0d14;
  }

  .dot--online {
    background: #34d399;
  }

  .dot--sm {
    height: 0.5rem;
    width: 0.5rem;
  }
  .dot--md {
    height: 0.625rem;
    width: 0.625rem;
  }
  .dot--lg {
    height: 0.875rem;
    width: 0.875rem;
  }
  .dot--xl {
    height: 1.25rem;
    width: 1.25rem;
  }
</style>

// src/catalog/data-display/avatar/Avatar.tsx
type AvatarSize = "sm" | "md" | "lg" | "xl";

interface AvatarProps {
  name: string;
  size?: AvatarSize;
  online?: boolean;
}

const SIZE_CLASSES: Record<AvatarSize, string> = {
  sm: "h-8 w-8 text-xs",
  md: "h-10 w-10 text-sm",
  lg: "h-14 w-14 text-lg",
  xl: "h-20 w-20 text-2xl",
};

const DOT_CLASSES: Record<AvatarSize, string> = {
  sm: "h-2 w-2",
  md: "h-2.5 w-2.5",
  lg: "h-3.5 w-3.5",
  xl: "h-5 w-5",
};

const PALETTE = [
  "bg-rose-500",
  "bg-orange-500",
  "bg-amber-500",
  "bg-emerald-500",
  "bg-teal-500",
  "bg-sky-500",
  "bg-indigo-500",
  "bg-violet-500",
  "bg-fuchsia-500",
];

function initials(name: string) {
  const parts = name.trim().split(/\s+/);
  const first = parts[0]?.[0] ?? "";
  const last = parts.length > 1 ? parts[parts.length - 1][0] : "";
  return (first + last).toUpperCase();
}

function colorFor(name: string) {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = (hash * 31 + name.charCodeAt(i)) >>> 0;
  }
  return PALETTE[hash % PALETTE.length];
}

export function Avatar({ name, size = "md", online }: AvatarProps) {
  return (
    <span className="relative inline-flex">
      <span
        className={`inline-flex items-center justify-center rounded-full font-semibold text-white select-none ${SIZE_CLASSES[size]} ${colorFor(
          name,
        )}`}
        title={name}
      >
        {initials(name)}
      </span>
      {online !== undefined && (
        <span
          className={`absolute bottom-0 right-0 rounded-full ring-2 ring-[#0d0d14] ${DOT_CLASSES[size]} ${
            online ? "bg-emerald-400" : "bg-slate-500"
          }`}
        />
      )}
    </span>
  );
}
