// src/catalog/data-display/tag/Tag.svelte
<script lang="ts">
  type TagColor = "slate" | "indigo" | "emerald" | "amber" | "rose";

  interface TagItem {
    id: number;
    label: string;
    color: TagColor;
  }

  const initialTags: TagItem[] = [
    { id: 1, label: "React", color: "indigo" },
    { id: 2, label: "TypeScript", color: "emerald" },
    { id: 3, label: "Tailwind", color: "amber" },
    { id: 4, label: "Vite", color: "rose" },
  ];

  let tags: TagItem[] = [...initialTags];

  function remove(id: number) {
    tags = tags.filter((t) => t.id !== id);
  }

  function reset() {
    tags = [...initialTags];
  }
</script>

<div class="tag-list">
  {#if tags.length === 0}
    <button type="button" class="reset" on:click={reset}>Reset tags</button>
  {:else}
    {#each tags as tag (tag.id)}
      <span class="tag tag--{tag.color}">
        {tag.label}
        <button
          type="button"
          class="tag__remove"
          aria-label={`Remove ${tag.label}`}
          on:click={() => remove(tag.id)}
        >
          <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
            <path
              d="M1 1l8 8M9 1l-8 8"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linecap="round"
            />
          </svg>
        </button>
      </span>
    {/each}
  {/if}
</div>

<style>
  .tag-list {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
  }

  .tag {
    display: inline-flex;
    align-items: center;
    gap: 0.375rem;
    border-radius: 9999px;
    padding: 0.25rem 0.75rem;
    font-size: 0.875rem;
    font-weight: 500;
    box-shadow: inset 0 0 0 1px var(--ring);
    color: var(--fg);
    background: var(--bg);
  }

  .tag--slate {
    --bg: rgba(100, 116, 139, 0.15);
    --fg: #cbd5e1;
    --ring: rgba(148, 163, 184, 0.2);
  }
  .tag--indigo {
    --bg: rgba(99, 102, 241, 0.15);
    --fg: #a5b4fc;
    --ring: rgba(129, 140, 248, 0.2);
  }
  .tag--emerald {
    --bg: rgba(16, 185, 129, 0.15);
    --fg: #6ee7b7;
    --ring: rgba(52, 211, 153, 0.2);
  }
  .tag--amber {
    --bg: rgba(245, 158, 11, 0.15);
    --fg: #fcd34d;
    --ring: rgba(251, 191, 36, 0.2);
  }
  .tag--rose {
    --bg: rgba(244, 63, 94, 0.15);
    --fg: #fda4af;
    --ring: rgba(251, 113, 133, 0.2);
  }

  .tag__remove {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    height: 1rem;
    width: 1rem;
    margin-right: -0.25rem;
    border: none;
    padding: 0;
    border-radius: 9999px;
    background: transparent;
    color: currentColor;
    cursor: pointer;
    transition: background-color 0.15s ease;
  }

  .tag__remove:hover {
    background: rgba(255, 255, 255, 0.15);
  }

  .reset {
    border-radius: 9999px;
    padding: 0.25rem 0.75rem;
    font-size: 0.875rem;
    font-weight: 500;
    color: #94a3b8;
    background: transparent;
    box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.15);
    cursor: pointer;
    transition: color 0.15s ease;
  }

  .reset:hover {
    color: #e2e8f0;
  }
</style>

// src/catalog/data-display/tag/Tag.tsx
import { useState } from "react";

type TagColor = "slate" | "indigo" | "emerald" | "amber" | "rose";

const COLOR_CLASSES: Record<TagColor, string> = {
  slate: "bg-slate-500/15 text-slate-300 ring-slate-400/20",
  indigo: "bg-indigo-500/15 text-indigo-300 ring-indigo-400/20",
  emerald: "bg-emerald-500/15 text-emerald-300 ring-emerald-400/20",
  amber: "bg-amber-500/15 text-amber-300 ring-amber-400/20",
  rose: "bg-rose-500/15 text-rose-300 ring-rose-400/20",
};

interface TagProps {
  label: string;
  color?: TagColor;
  onRemove?: () => void;
}

export function Tag({ label, color = "slate", onRemove }: TagProps) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-sm font-medium ring-1 ring-inset ${COLOR_CLASSES[color]}`}
    >
      {label}
      {onRemove && (
        <button
          type="button"
          onClick={onRemove}
          aria-label={`Remove ${label}`}
          className="-mr-1 inline-flex h-4 w-4 items-center justify-center rounded-full text-current transition-colors hover:bg-white/15"
        >
          <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
            <path
              d="M1 1l8 8M9 1l-8 8"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
          </svg>
        </button>
      )}
    </span>
  );
}

interface TagItem {
  id: number;
  label: string;
  color: TagColor;
}

const INITIAL_TAGS: TagItem[] = [
  { id: 1, label: "React", color: "indigo" },
  { id: 2, label: "TypeScript", color: "emerald" },
  { id: 3, label: "Tailwind", color: "amber" },
  { id: 4, label: "Vite", color: "rose" },
];

export function TagList() {
  const [tags, setTags] = useState<TagItem[]>(INITIAL_TAGS);

  function remove(id: number) {
    setTags((prev) => prev.filter((t) => t.id !== id));
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      {tags.length === 0 ? (
        <button
          type="button"
          onClick={() => setTags(INITIAL_TAGS)}
          className="rounded-full px-3 py-1 text-sm font-medium text-slate-400 ring-1 ring-inset ring-white/15 transition-colors hover:text-slate-200"
        >
          Reset tags
        </button>
      ) : (
        tags.map((tag) => (
          <Tag
            key={tag.id}
            label={tag.label}
            color={tag.color}
            onRemove={() => remove(tag.id)}
          />
        ))
      )}
    </div>
  );
}
