// src/catalog/forms/radio-group/RadioGroup.svelte
<script lang="ts">
  export interface RadioOption {
    value: string;
    label: string;
    description?: string;
  }

  export let options: RadioOption[] = [];
  export let name: string = "radio-group";
  export let selected: string = options[0]?.value;

  function select(value: string) {
    selected = value;
  }
</script>

<div role="radiogroup" class="radio-group">
  {#each options as option (option.value)}
    <label class="radio-option" class:checked={option.value === selected}>
      <input
        type="radio"
        {name}
        value={option.value}
        checked={option.value === selected}
        on:change={() => select(option.value)}
        class="radio-input"
      />
      <span class="radio-dot" class:checked={option.value === selected} aria-hidden="true">
        <span class="radio-dot__inner"></span>
      </span>
      <span class="radio-text">
        <span class="radio-label">{option.label}</span>
        {#if option.description}
          <span class="radio-description">{option.description}</span>
        {/if}
      </span>
    </label>
  {/each}
</div>

<style>
  .radio-group {
    display: flex;
    width: 100%;
    flex-direction: column;
    gap: 0.625rem;
  }

  .radio-option {
    display: flex;
    cursor: pointer;
    align-items: flex-start;
    gap: 0.75rem;
    border-radius: 0.75rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: rgba(255, 255, 255, 0.03);
    padding: 0.75rem;
    transition: border-color 0.18s ease, background 0.18s ease;
  }

  .radio-option:hover {
    border-color: rgba(255, 255, 255, 0.2);
  }

  .radio-option.checked {
    border-color: rgba(129, 140, 248, 0.7);
    background: rgba(99, 102, 241, 0.1);
  }

  .radio-input {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }

  .radio-dot {
    display: flex;
    margin-top: 0.125rem;
    height: 1.25rem;
    width: 1.25rem;
    flex-shrink: 0;
    align-items: center;
    justify-content: center;
    border-radius: 9999px;
    border: 2px solid rgba(255, 255, 255, 0.3);
    transition: border-color 0.18s ease;
  }

  .radio-dot.checked {
    border-color: #818cf8;
  }

  .radio-dot__inner {
    height: 0.625rem;
    width: 0.625rem;
    border-radius: 9999px;
    background: linear-gradient(135deg, #818cf8, #e879f9);
    transform: scale(0);
    transition: transform 0.15s ease;
  }

  .radio-dot.checked .radio-dot__inner {
    transform: scale(1);
  }

  .radio-text {
    display: flex;
    flex-direction: column;
  }

  .radio-label {
    font-size: 0.875rem;
    font-weight: 500;
    color: #f8f8fc;
  }

  .radio-description {
    font-size: 0.75rem;
    color: rgba(255, 255, 255, 0.5);
  }
</style>

// src/catalog/forms/radio-group/RadioGroup.tsx
import { useState } from "react";

export interface RadioOption {
  value: string;
  label: string;
  description?: string;
}

interface RadioGroupProps {
  options: RadioOption[];
  name?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
}

export function RadioGroup({
  options,
  name = "radio-group",
  defaultValue,
  onChange,
}: RadioGroupProps) {
  const [selected, setSelected] = useState(defaultValue ?? options[0]?.value);

  function select(value: string) {
    setSelected(value);
    onChange?.(value);
  }

  return (
    <div role="radiogroup" className="flex w-full flex-col gap-2.5">
      {options.map((option) => {
        const checked = option.value === selected;
        return (
          <label
            key={option.value}
            className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition ${
              checked
                ? "border-indigo-400/70 bg-indigo-500/10"
                : "border-white/10 bg-white/[0.03] hover:border-white/20"
            }`}
          >
            <input
              type="radio"
              name={name}
              value={option.value}
              checked={checked}
              onChange={() => select(option.value)}
              className="sr-only"
            />
            <span
              aria-hidden="true"
              className={`mt-0.5 flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-full border-2 transition ${
                checked ? "border-indigo-400" : "border-white/30"
              }`}
            >
              <span
                className={`h-2.5 w-2.5 rounded-full bg-gradient-to-br from-indigo-400 to-fuchsia-400 transition-transform duration-150 ${
                  checked ? "scale-100" : "scale-0"
                }`}
              />
            </span>
            <span className="flex flex-col">
              <span className="text-sm font-medium text-[#f8f8fc]">
                {option.label}
              </span>
              {option.description && (
                <span className="text-xs text-white/50">
                  {option.description}
                </span>
              )}
            </span>
          </label>
        );
      })}
    </div>
  );
}
