// src/catalog/layout/grid/Grid.svelte
<script lang="ts">
  export let minColumnWidth: string = "12rem";
  export let gap: string = "1rem";
</script>

<div
  class="auto-grid"
  style="--grid-min: {minColumnWidth}; --grid-gap: {gap};"
>
  <slot />
</div>

<style>
  .auto-grid {
    --grid-min: 12rem;
    --grid-gap: 1rem;
    display: grid;
    gap: var(--grid-gap);
    /* Reflows automatically by available width: as many columns as fit,
       each at least --grid-min wide, sharing leftover space equally. */
    grid-template-columns: repeat(auto-fill, minmax(var(--grid-min), 1fr));
  }
</style>

// src/catalog/layout/grid/Grid.tsx
import "./Grid.css";
import type { ReactNode } from "react";

interface GridProps {
  children?: ReactNode;
  /** Minimum width of each column before the grid reflows, e.g. "12rem". */
  minColumnWidth?: string;
  /** Gap between grid items. */
  gap?: string;
}

export function Grid({
  children,
  minColumnWidth = "12rem",
  gap = "1rem",
}: GridProps) {
  return (
    <div
      className="auto-grid"
      style={{
        // CSS custom properties drive the auto-fill / minmax track sizing.
        ["--grid-min" as string]: minColumnWidth,
        ["--grid-gap" as string]: gap,
      }}
    >
      {children}
    </div>
  );
}
