// src/catalog/forms/date-picker/DatePicker.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  export let value: Date | null = null;
  export let placeholder: string = "Pick a date";

  const WEEKDAYS = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];
  const MONTHS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  let open = false;
  let rootEl: HTMLDivElement;

  const initial = value ?? new Date();
  let viewYear = initial.getFullYear();
  let viewMonth = initial.getMonth();

  const today = new Date();

  function startOfDay(date: Date): Date {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate());
  }

  function isSameDay(a: Date, b: Date): boolean {
    return startOfDay(a).getTime() === startOfDay(b).getTime();
  }

  function formatField(date: Date | null): string {
    if (!date) return "";
    return `${MONTHS[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;
  }

  function buildGrid(year: number, month: number): Date[] {
    const firstOfMonth = new Date(year, month, 1);
    const gridStart = new Date(firstOfMonth);
    gridStart.setDate(1 - firstOfMonth.getDay());
    const cells: Date[] = [];
    for (let i = 0; i < 42; i++) {
      const day = new Date(gridStart);
      day.setDate(gridStart.getDate() + i);
      cells.push(day);
    }
    return cells;
  }

  $: grid = buildGrid(viewYear, viewMonth);

  function goToMonth(delta: number) {
    const next = new Date(viewYear, viewMonth + delta, 1);
    viewYear = next.getFullYear();
    viewMonth = next.getMonth();
  }

  function choose(day: Date) {
    value = day;
    viewYear = day.getFullYear();
    viewMonth = day.getMonth();
    open = false;
  }

  function onPointerDown(event: MouseEvent) {
    if (rootEl && !rootEl.contains(event.target as Node)) {
      open = false;
    }
  }
  function onKeyDown(event: KeyboardEvent) {
    if (event.key === "Escape") open = false;
  }

  function setListeners(active: boolean) {
    if (active) {
      document.addEventListener("mousedown", onPointerDown);
      document.addEventListener("keydown", onKeyDown);
    } else {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    }
  }

  $: setListeners(open);

  onDestroy(() => setListeners(false));
</script>

<div bind:this={rootEl} class="dp">
  <button
    type="button"
    aria-haspopup="dialog"
    aria-expanded={open}
    class="dp__field"
    on:click={() => (open = !open)}
  >
    <span class="dp__value" class:placeholder={!value}>
      {value ? formatField(value) : placeholder}
    </span>
    <svg
      class="dp__icon"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <rect x="3" y="4" width="18" height="18" rx="2" />
      <line x1="16" y1="2" x2="16" y2="6" />
      <line x1="8" y1="2" x2="8" y2="6" />
      <line x1="3" y1="10" x2="21" y2="10" />
    </svg>
  </button>

  {#if open}
    <div role="dialog" aria-label="Choose a date" class="dp__popover">
      <div class="dp__header">
        <button
          type="button"
          aria-label="Previous month"
          class="dp__nav"
          on:click={() => goToMonth(-1)}
        >
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </button>
        <span class="dp__title">{MONTHS[viewMonth]} {viewYear}</span>
        <button
          type="button"
          aria-label="Next month"
          class="dp__nav"
          on:click={() => goToMonth(1)}
        >
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </button>
      </div>

      <div class="dp__weekdays">
        {#each WEEKDAYS as day}
          <span class="dp__weekday">{day}</span>
        {/each}
      </div>

      <div class="dp__grid">
        {#each grid as day (day.toISOString())}
          <button
            type="button"
            aria-label={formatField(day)}
            aria-selected={value ? isSameDay(day, value) : false}
            class="dp__day"
            class:selected={value ? isSameDay(day, value) : false}
            class:today={isSameDay(day, today) &&
              !(value && isSameDay(day, value))}
            class:outside={day.getMonth() !== viewMonth}
            on:click={() => choose(day)}
          >
            {day.getDate()}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
  .dp {
    position: relative;
    width: 100%;
  }

  .dp__field {
    display: flex;
    width: 100%;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    border-radius: 0.5rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: rgba(255, 255, 255, 0.03);
    padding: 0.625rem 0.875rem;
    text-align: left;
    font-size: 0.875rem;
    color: #f8f8fc;
    cursor: pointer;
    outline: none;
    transition: border-color 0.18s ease, box-shadow 0.18s ease;
  }

  .dp__field:focus-visible {
    border-color: #818cf8;
    box-shadow: 0 0 0 2px rgba(129, 140, 248, 0.25);
  }

  .dp__value.placeholder {
    color: rgba(255, 255, 255, 0.4);
  }

  .dp__icon {
    height: 1rem;
    width: 1rem;
    flex-shrink: 0;
    color: rgba(255, 255, 255, 0.5);
  }

  .dp__popover {
    position: absolute;
    z-index: 10;
    margin-top: 0.5rem;
    width: 18rem;
    border-radius: 0.75rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: #15151f;
    padding: 0.75rem;
    box-shadow: 0 20px 50px -12px rgba(0, 0, 0, 0.5);
  }

  .dp__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 0.5rem;
  }

  .dp__nav {
    display: flex;
    height: 2rem;
    width: 2rem;
    align-items: center;
    justify-content: center;
    border: none;
    border-radius: 0.375rem;
    background: transparent;
    color: rgba(255, 255, 255, 0.7);
    cursor: pointer;
    transition: background 0.15s ease, color 0.15s ease;
  }

  .dp__nav:hover {
    background: rgba(255, 255, 255, 0.1);
    color: #fff;
  }

  .dp__nav svg {
    height: 1rem;
    width: 1rem;
  }

  .dp__title {
    font-size: 0.875rem;
    font-weight: 600;
    color: #f8f8fc;
  }

  .dp__weekdays,
  .dp__grid {
    display: grid;
    grid-template-columns: repeat(7, minmax(0, 1fr));
    gap: 0.25rem;
  }

  .dp__weekdays {
    margin-bottom: 0.25rem;
  }

  .dp__weekday {
    display: flex;
    height: 2rem;
    align-items: center;
    justify-content: center;
    font-size: 0.75rem;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.4);
  }

  .dp__day {
    display: flex;
    height: 2rem;
    width: 100%;
    align-items: center;
    justify-content: center;
    border: none;
    border-radius: 0.375rem;
    background: transparent;
    font-size: 0.875rem;
    color: rgba(255, 255, 255, 0.85);
    cursor: pointer;
    transition: background 0.15s ease;
  }

  .dp__day:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  .dp__day.outside {
    color: rgba(255, 255, 255, 0.3);
  }

  .dp__day.outside:hover {
    background: rgba(255, 255, 255, 0.05);
  }

  .dp__day.today {
    border: 1px solid rgba(129, 140, 248, 0.6);
    color: #f8f8fc;
  }

  .dp__day.selected {
    background: linear-gradient(135deg, #6366f1, #d946ef);
    font-weight: 600;
    color: #fff;
  }
</style>

// src/catalog/forms/date-picker/DatePicker.tsx
import { useEffect, useRef, useState } from "react";

const WEEKDAYS = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];
const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

function startOfDay(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function isSameDay(a: Date, b: Date): boolean {
  return startOfDay(a).getTime() === startOfDay(b).getTime();
}

function formatField(date: Date | null): string {
  if (!date) return "";
  return `${MONTHS[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;
}

/** Build a 6-row x 7-col grid of dates covering the given month. */
function buildGrid(viewYear: number, viewMonth: number): Date[] {
  const firstOfMonth = new Date(viewYear, viewMonth, 1);
  const gridStart = new Date(firstOfMonth);
  gridStart.setDate(1 - firstOfMonth.getDay());

  const cells: Date[] = [];
  for (let i = 0; i < 42; i++) {
    const day = new Date(gridStart);
    day.setDate(gridStart.getDate() + i);
    cells.push(day);
  }
  return cells;
}

interface DatePickerProps {
  defaultValue?: Date;
  placeholder?: string;
  onChange?: (date: Date) => void;
}

export function DatePicker({
  defaultValue,
  placeholder = "Pick a date",
  onChange,
}: DatePickerProps) {
  const [open, setOpen] = useState(false);
  const [selected, setSelected] = useState<Date | null>(defaultValue ?? null);
  const initial = defaultValue ?? new Date();
  const [viewYear, setViewYear] = useState(initial.getFullYear());
  const [viewMonth, setViewMonth] = useState(initial.getMonth());
  const rootRef = useRef<HTMLDivElement>(null);

  const today = new Date();

  useEffect(() => {
    if (!open) return;

    function onPointerDown(event: MouseEvent) {
      if (rootRef.current && !rootRef.current.contains(event.target as Node)) {
        setOpen(false);
      }
    }
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") setOpen(false);
    }

    document.addEventListener("mousedown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);

  function goToMonth(delta: number) {
    const next = new Date(viewYear, viewMonth + delta, 1);
    setViewYear(next.getFullYear());
    setViewMonth(next.getMonth());
  }

  function choose(day: Date) {
    setSelected(day);
    setViewYear(day.getFullYear());
    setViewMonth(day.getMonth());
    onChange?.(day);
    setOpen(false);
  }

  const grid = buildGrid(viewYear, viewMonth);

  return (
    <div ref={rootRef} className="relative w-full">
      <button
        type="button"
        aria-haspopup="dialog"
        aria-expanded={open}
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between gap-2 rounded-lg border border-white/10 bg-white/[0.03] px-3.5 py-2.5 text-left text-sm outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/25"
      >
        <span className={selected ? "text-[#f8f8fc]" : "text-white/40"}>
          {selected ? formatField(selected) : placeholder}
        </span>
        <svg
          className="h-4 w-4 flex-shrink-0 text-white/50"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <rect x="3" y="4" width="18" height="18" rx="2" />
          <line x1="16" y1="2" x2="16" y2="6" />
          <line x1="8" y1="2" x2="8" y2="6" />
          <line x1="3" y1="10" x2="21" y2="10" />
        </svg>
      </button>

      {open && (
        <div
          role="dialog"
          aria-label="Choose a date"
          className="absolute z-10 mt-2 w-72 rounded-xl border border-white/10 bg-[#15151f] p-3 shadow-2xl shadow-black/50"
        >
          <div className="mb-2 flex items-center justify-between">
            <button
              type="button"
              aria-label="Previous month"
              onClick={() => goToMonth(-1)}
              className="flex h-8 w-8 items-center justify-center rounded-md text-white/70 transition hover:bg-white/10 hover:text-white"
            >
              <svg
                className="h-4 w-4"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <polyline points="15 18 9 12 15 6" />
              </svg>
            </button>
            <span className="text-sm font-semibold text-[#f8f8fc]">
              {MONTHS[viewMonth]} {viewYear}
            </span>
            <button
              type="button"
              aria-label="Next month"
              onClick={() => goToMonth(1)}
              className="flex h-8 w-8 items-center justify-center rounded-md text-white/70 transition hover:bg-white/10 hover:text-white"
            >
              <svg
                className="h-4 w-4"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <polyline points="9 18 15 12 9 6" />
              </svg>
            </button>
          </div>

          <div className="mb-1 grid grid-cols-7 gap-1">
            {WEEKDAYS.map((day) => (
              <span
                key={day}
                className="flex h-8 items-center justify-center text-xs font-medium text-white/40"
              >
                {day}
              </span>
            ))}
          </div>

          <div className="grid grid-cols-7 gap-1">
            {grid.map((day) => {
              const inMonth = day.getMonth() === viewMonth;
              const isToday = isSameDay(day, today);
              const isSelected = selected ? isSameDay(day, selected) : false;
              return (
                <button
                  key={day.toISOString()}
                  type="button"
                  aria-label={formatField(day)}
                  aria-selected={isSelected}
                  onClick={() => choose(day)}
                  className={`flex h-8 w-full items-center justify-center rounded-md text-sm transition ${
                    isSelected
                      ? "bg-gradient-to-br from-indigo-500 to-fuchsia-500 font-semibold text-white"
                      : isToday
                      ? "border border-indigo-400/60 text-[#f8f8fc] hover:bg-white/10"
                      : inMonth
                      ? "text-white/85 hover:bg-white/10"
                      : "text-white/30 hover:bg-white/5"
                  }`}
                >
                  {day.getDate()}
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
