// src/catalog/forms/select/Select.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  export interface SelectOption {
    value: string;
    label: string;
  }

  export let options: SelectOption[] = [];
  export let value: string = "";
  export let placeholder: string = "Select an option";

  let open = false;
  let rootEl: HTMLDivElement;

  $: selected = options.find((o) => o.value === value);

  function onPointerDown(event: MouseEvent) {
    if (rootEl && !rootEl.contains(event.target as Node)) {
      open = false;
    }
  }
  function onKeyDown(event: KeyboardEvent) {
    if (event.key === "Escape") open = false;
  }

  function setListeners(active: boolean) {
    if (active) {
      document.addEventListener("mousedown", onPointerDown);
      document.addEventListener("keydown", onKeyDown);
    } else {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    }
  }

  $: setListeners(open);

  function choose(option: SelectOption) {
    value = option.value;
    open = false;
  }

  onDestroy(() => setListeners(false));
</script>

<div bind:this={rootEl} class="select">
  <button
    type="button"
    aria-haspopup="listbox"
    aria-expanded={open}
    class="select__trigger"
    on:click={() => (open = !open)}
  >
    <span class="select__value" class:placeholder={!selected}>
      {selected ? selected.label : placeholder}
    </span>
    <svg
      class="select__chevron"
      class:open
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  </button>

  {#if open}
    <ul role="listbox" class="select__list">
      {#each options as option (option.value)}
        <li role="option" aria-selected={option.value === value}>
          <button
            type="button"
            class="select__option"
            class:selected={option.value === value}
            on:click={() => choose(option)}
          >
            <span>{option.label}</span>
            {#if option.value === value}
              <svg
                class="select__check"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2.5"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <polyline points="20 6 9 17 4 12" />
              </svg>
            {/if}
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</div>

<style>
  .select {
    position: relative;
    width: 100%;
  }

  .select__trigger {
    display: flex;
    width: 100%;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    border-radius: 0.5rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: rgba(255, 255, 255, 0.03);
    padding: 0.625rem 0.875rem;
    text-align: left;
    font-size: 0.875rem;
    color: #f8f8fc;
    cursor: pointer;
    outline: none;
    transition: border-color 0.18s ease, box-shadow 0.18s ease;
  }

  .select__trigger:focus-visible {
    border-color: #818cf8;
    box-shadow: 0 0 0 2px rgba(129, 140, 248, 0.25);
  }

  .select__value.placeholder {
    color: rgba(255, 255, 255, 0.4);
  }

  .select__chevron {
    height: 1rem;
    width: 1rem;
    flex-shrink: 0;
    color: rgba(255, 255, 255, 0.5);
    transition: transform 0.2s ease;
  }

  .select__chevron.open {
    transform: rotate(180deg);
  }

  .select__list {
    position: absolute;
    z-index: 10;
    margin-top: 0.5rem;
    max-height: 15rem;
    width: 100%;
    overflow: auto;
    list-style: none;
    border-radius: 0.5rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: #15151f;
    padding: 0.25rem;
    margin-block: 0.5rem 0;
    box-shadow: 0 20px 50px -12px rgba(0, 0, 0, 0.5);
  }

  .select__option {
    display: flex;
    width: 100%;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    border: none;
    border-radius: 0.375rem;
    background: transparent;
    padding: 0.5rem 0.75rem;
    text-align: left;
    font-size: 0.875rem;
    color: rgba(255, 255, 255, 0.8);
    cursor: pointer;
    transition: background 0.15s ease;
  }

  .select__option:hover {
    background: rgba(255, 255, 255, 0.05);
  }

  .select__option.selected {
    background: rgba(99, 102, 241, 0.2);
    color: #f8f8fc;
  }

  .select__check {
    height: 1rem;
    width: 1rem;
    color: #a5b4fc;
  }
</style>

// src/catalog/forms/select/Select.tsx
import { useEffect, useId, useRef, useState } from "react";

export interface SelectOption {
  value: string;
  label: string;
}

interface SelectProps {
  options: SelectOption[];
  defaultValue?: string;
  placeholder?: string;
  onChange?: (value: string) => void;
}

export function Select({
  options,
  defaultValue,
  placeholder = "Select an option",
  onChange,
}: SelectProps) {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState(defaultValue ?? "");
  const rootRef = useRef<HTMLDivElement>(null);
  const listId = useId();

  const selected = options.find((o) => o.value === value);

  useEffect(() => {
    if (!open) return;

    function onPointerDown(event: MouseEvent) {
      if (rootRef.current && !rootRef.current.contains(event.target as Node)) {
        setOpen(false);
      }
    }
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") setOpen(false);
    }

    document.addEventListener("mousedown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);

  function choose(option: SelectOption) {
    setValue(option.value);
    onChange?.(option.value);
    setOpen(false);
  }

  return (
    <div ref={rootRef} className="relative w-full">
      <button
        type="button"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-controls={listId}
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between gap-2 rounded-lg border border-white/10 bg-white/[0.03] px-3.5 py-2.5 text-left text-sm outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/25"
      >
        <span className={selected ? "text-[#f8f8fc]" : "text-white/40"}>
          {selected ? selected.label : placeholder}
        </span>
        <svg
          className={`h-4 w-4 flex-shrink-0 text-white/50 transition-transform duration-200 ${
            open ? "rotate-180" : ""
          }`}
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </button>

      {open && (
        <ul
          id={listId}
          role="listbox"
          className="absolute z-10 mt-2 max-h-60 w-full overflow-auto rounded-lg border border-white/10 bg-[#15151f] p-1 shadow-2xl shadow-black/50"
        >
          {options.map((option) => {
            const isSelected = option.value === value;
            return (
              <li key={option.value} role="option" aria-selected={isSelected}>
                <button
                  type="button"
                  onClick={() => choose(option)}
                  className={`flex w-full items-center justify-between gap-2 rounded-md px-3 py-2 text-left text-sm transition ${
                    isSelected
                      ? "bg-indigo-500/20 text-[#f8f8fc]"
                      : "text-white/80 hover:bg-white/5"
                  }`}
                >
                  <span>{option.label}</span>
                  {isSelected && (
                    <svg
                      className="h-4 w-4 text-indigo-300"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden="true"
                    >
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  )}
                </button>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
